# Generated by Django on 2025-05-21
from django.db import migrations

MALE_NAMES = [
    "João", "Pedro", "Lucas", "Gabriel", "Matheus",
    "Leonardo", "Gustavo", "Felipe", "Daniel", "Thiago",
    "Bruno", "André", "Ricardo", "Eduardo", "Alexandre",
    "Henrique", "Rafael", "Diego", "Victor", "Samuel",
    "Fernando", "Marcelo", "Antônio", "Rodrigo", "Carlos",
    "Adriano", "Vinícius", "Caio", "Fábio", "Igor",
    "Júlio", "Cristian", "Emanuel", "Renan", "Roberto",
    "Márcio", "Nelson", "Wagner", "Sebastião", "Otávio",
    "Raul", "Osvaldo", "Sérgio", "Luciano", "Mauro",
    "Elias", "Marcos", "José", "Heitor"
]

FEMALE_NAMES = [
    "Maria", "Ana", "Júlia", "Mariana", "Beatriz",
    "Camila", "Rafaela", "Sofia", "Isabela", "Carolina",
    "Fernanda", "Larissa", "Vanessa", "Luana", "Gabriela",
    "Tatiane", "Renata", "Patrícia", "Sandra", "Cláudia",
    "Bruna", "Alessandra", "Simone", "Thaís", "Bianca",
    "Cecília", "Natália", "Vitória", "Helena", "Cristiane",
    "Débora", "Letícia", "Roberta", "Daniela", "Elisângela",
    "Flávia", "Juliane", "Ivana", "Elaine", "Michelle",
    "Sílvia", "Jéssica", "Marisa", "Estela", "Ludmila",
    "Mônica", "Regina", "Tatiana", "Adriana", "Paula"
]

SURNAMES = [
    "Silva", "Santos", "Oliveira", "Sousa", "Lima",
    "Costa", "Pereira", "Carvalho", "Rodrigues", "Almeida",
    "Nunes", "Castro", "Freitas", "Gomes", "Fernandes",
    "Martins", "Moreira", "Azevedo", "Monteiro", "Teixeira",
    "Medeiros", "Cardoso", "Bezerra", "Vieira", "Machado",
    "Campos", "Tavares", "Moraes", "Guimarães", "Cunha",
    "Figueiredo", "Barreto", "Ávila", "Andrade", "Aragão",
    "Brito", "Reis", "Fonseca", "Melo", "Bastos",
    "Corrêa", "Passos", "Sales", "Siqueira", "Navarro",
    "Dantas", "Coutinho", "Neves", "Rangel", "Queiroz",
    "Albuquerque", "Bastiani", "Benício", "Bianchi", "Brandão",
    "Camargo", "Capelo", "Caruso", "Damiani", "Domenici",
    "Espinosa", "Fraga", "Lacerda", "Lancastre", "Mendonça",
    "Montanha", "Pasqualini", "Quintana", "Sarmiento", "Toscano"
]

def load_initial_names(apps, schema_editor):
    GivenName = apps.get_model('names', 'GivenName')
    Surname = apps.get_model('names', 'Surname')
    # Populate given names
    for name in MALE_NAMES:
        GivenName.objects.get_or_create(name=name, gender='M')
    for name in FEMALE_NAMES:
        GivenName.objects.get_or_create(name=name, gender='F')
    # Populate surnames
    for name in SURNAMES:
        Surname.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_names),
    ]
